# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NQNpw5miWY2UVy5FMPShy2Xnrf0mvITF
"""

import matplotlib.pyplot as plt
import pandas as pd
from sklearn import metrics
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

data = load_breast_cancer(as_frame=True)
data["data"].head()
data["target"].head()

X = data['data']
y = data['target']

X.head()

X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.25, random_state=0)

scaler_train = StandardScaler()
scaler_test = StandardScaler()

X_train = scaler_train.fit_transform(X_train)
X_test = scaler_test.fit_transform(X_test)

model = LogisticRegression(random_state=16)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

"""# **Plotting confusion matrix**"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

class_names = [0,1]
fig, ax = plt.subplots()
tick_marks = np.arange(2)
plt.xticks(tick_marks, class_names)
plt.yticks(tick_marks, class_names)

cnf_df = pd.DataFrame(cnf_matrix)
sns.heatmap(cnf_df, annot=True, cmap="YlGnBu", fmt="g")
ax.xaxis.set_label_position("top")
plt.tight_layout()
plt.title("Confusion Matrix")
plt.ylabel("Actual Result")
plt.xlabel("Predicted Result")

"""# **Getting Accuracy**"""

from sklearn.metrics import classification_report
target_names = ["Benign", "Malign"]
print(classification_report(y_test, y_pred, target_names=target_names))